export const mangaData = [
  {
    id: 1,
    title: "Chainsaw Man",
    author: "Tatsuki Fujimoto",
    rating: 4.8,
    chapters: 97,
    status: "Ongoing",
    genres: ["Action", "Supernatural", "Drama"],
    image: "https://images.pexels.com/photos/2480391/pexels-photo-2480391.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "2.1M",
    lastUpdated: "2 days ago",
    description: "Denji has a simple dream—to live a happy and peaceful life."
  },
  {
    id: 2,
    title: "Jujutsu Kaisen",
    author: "Gege Akutami",
    rating: 4.7,
    chapters: 236,
    status: "Ongoing",
    genres: ["Action", "Supernatural", "School"],
    image: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "3.5M",
    lastUpdated: "1 week ago",
    description: "A high schooler gains the power to fight supernatural forces."
  },
  {
    id: 3,
    title: "My Hero Academia",
    author: "Kohei Horikoshi",
    rating: 4.6,
    chapters: 403,
    status: "Ongoing",
    genres: ["Action", "Superhero", "School"],
    image: "https://images.pexels.com/photos/2480391/pexels-photo-2480391.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "4.2M",
    lastUpdated: "3 days ago",
    description: "In a world where superpowers are common, one boy dreams of becoming a hero."
  },
  {
    id: 4,
    title: "Tokyo Revengers",
    author: "Ken Wakui",
    rating: 4.5,
    chapters: 278,
    status: "Completed",
    genres: ["Action", "Drama", "Time Travel"],
    image: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "2.8M",
    lastUpdated: "1 month ago",
    description: "A man travels back in time to prevent a tragedy."
  },
  {
    id: 5,
    title: "Spy x Family",
    author: "Tatsuya Endo",
    rating: 4.9,
    chapters: 89,
    status: "Ongoing",
    genres: ["Comedy", "Action", "Family"],
    image: "https://images.pexels.com/photos/2480391/pexels-photo-2480391.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "5.1M",
    lastUpdated: "5 days ago",
    description: "A spy must build a fake family to maintain his cover."
  },
  {
    id: 6,
    title: "One Punch Man",
    author: "ONE, Yusuke Murata",
    rating: 4.8,
    chapters: 175,
    status: "Ongoing",
    genres: ["Action", "Comedy", "Superhero"],
    image: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "6.3M",
    lastUpdated: "1 week ago",
    description: "A hero who can defeat any enemy with a single punch."
  },
  {
    id: 7,
    title: "Death Note",
    author: "Tsugumi Ohba",
    rating: 4.7,
    chapters: 108,
    status: "Completed",
    genres: ["Thriller", "Supernatural", "Drama"],
    image: "https://images.pexels.com/photos/2480391/pexels-photo-2480391.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "8.1M",
    lastUpdated: "5 years ago",
    description: "A student finds a notebook that can kill anyone whose name is written in it."
  },
  {
    id: 8,
    title: "Naruto",
    author: "Masashi Kishimoto",
    rating: 4.6,
    chapters: 700,
    status: "Completed",
    genres: ["Action", "Adventure", "Ninja"],
    image: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "12.5M",
    lastUpdated: "8 years ago",
    description: "A young ninja's journey to become the strongest ninja and leader of his village."
  },
  {
    id: 9,
    title: "Hunter x Hunter",
    author: "Yoshihiro Togashi",
    rating: 4.9,
    chapters: 390,
    status: "Hiatus",
    genres: ["Adventure", "Fantasy", "Action"],
    image: "https://images.pexels.com/photos/2480391/pexels-photo-2480391.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "3.7M",
    lastUpdated: "2 years ago",
    description: "A young boy searches for his father while becoming a Hunter."
  },
  {
    id: 10,
    title: "Vinland Saga",
    author: "Makoto Yukimura",
    rating: 4.8,
    chapters: 199,
    status: "Ongoing",
    genres: ["Historical", "Drama", "Action"],
    image: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "1.9M",
    lastUpdated: "1 week ago",
    description: "A Viking saga of revenge, war, and the search for a peaceful land."
  },
  {
    id: 11,
    title: "Berserk",
    author: "Kentaro Miura",
    rating: 4.9,
    chapters: 371,
    status: "Hiatus",
    genres: ["Dark Fantasy", "Action", "Horror"],
    image: "https://images.pexels.com/photos/2480391/pexels-photo-2480391.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "2.6M",
    lastUpdated: "6 months ago",
    description: "A dark tale of revenge in a medieval fantasy world."
  },
  {
    id: 12,
    title: "Monster",
    author: "Naoki Urasawa",
    rating: 4.8,
    chapters: 162,
    status: "Completed",
    genres: ["Thriller", "Drama", "Mystery"],
    image: "https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    views: "1.4M",
    lastUpdated: "15 years ago",
    description: "A surgeon's life changes after saving a young boy who becomes a serial killer."
  }
];